apiVersion: resources.yatai.ai/v1alpha1
kind: BentoRequest
metadata:
  name: fraud-detection
  namespace: kubeflow
spec:
  bentoTag: fraud_detection:o5smnagbncigycvj
  downloadUrl: s3://bentoml.com/kubeflow/fraud_detection.bento
  runners:
  - name: ieee-fraud-detection-0
  - name: ieee-fraud-detection-1
  - name: ieee-fraud-detection-2
---
apiVersion: serving.yatai.ai/v2alpha1
kind: BentoDeployment
metadata:
  name: fraud-detection
  namespace: kubeflow
spec:
  autoscaling:
    maxReplicas: 2
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    minReplicas: 1
  bento: fraud-detection
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 200Mi
  runners:
  - autoscaling:
      maxReplicas: 2
      metrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
      minReplicas: 1
    name: ieee-fraud-detection-0
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 200Mi
  - autoscaling:
      maxReplicas: 2
      metrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
      minReplicas: 1
    name: ieee-fraud-detection-1
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 200Mi
  - autoscaling:
      maxReplicas: 2
      metrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
      minReplicas: 1
    name: ieee-fraud-detection-2
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 200Mi