ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "ci: auto fixes from pre-commit.ci\n\nFor more information, see https://pre-commit.ci"
  autoupdate_commit_msg: 'ci: pre-commit autoupdate [skip ci]'
  skip:  # exceeds tier max size
    - buf-format
    - buf-lint
exclude: '(.*\.(css|js|svg))|(.*/(snippets|grpc|proto)/.*)$'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]
        files: '(src|tests|docs|examples|typings)/'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pdm-project/pdm
    rev: 2.22.3
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/bufbuild/buf
    rev: v1.50.0
    hooks:
      - id: buf-format
        args: [--config=src/bentoml/grpc/buf.yaml, src/bentoml/grpc]
      - id: buf-lint
        args: [--config=src/bentoml/grpc/buf.yaml, --error-format=msvs, src/bentoml/grpc]
