version: 2
services:
  resources: ~
  workers: ~
  threads: 1
  backlog: 2048
  # the maximum number of connections that will be made to any given runner server at once
  max_runner_connections: 16
  # whether to start subprocess for each worker
  replicate_process: false
  extra_ports: ~
  runner_connection:
    max_requests: 100
    max_age: 300.0
  traffic:
    timeout: 60.0
    max_concurrency: ~
  metrics:
    enabled: true
    namespace: bentoml_service
    duration:
      # https://github.com/prometheus/client_python/blob/f17a8361ad3ed5bc47f193ac03b00911120a8d81/prometheus_client/metrics.py#L544
      buckets: ~
      min: ~
      max: ~
      factor: ~
  runner_probe: # configure whether the API server's health check endpoints (readyz, livez, healthz) also check the runners
    enabled: true
    timeout: 1
    period: 10
  logging:
    access:
      enabled: true
      request_content_length: true
      request_content_type: true
      response_content_length: true
      response_content_type: true
      skip_paths: ['/metrics', '/healthz', '/livez', '/readyz']
      format:
        trace_id: 032x
        span_id: 016x
  ssl:
    enabled: false
    certfile: ~
    keyfile: ~
    keyfile_password: ~
    ca_certs: ~
    version: 17 # ssl.PROTOCOL_TLS_SERVER
    cert_reqs: 0 # ssl.CERT_NONE
    ciphers: TLSv1 # default ciphers
  http:
    host: 0.0.0.0
    port: 3000
    proxy_port: 8000
    cors:
      enabled: false
      access_control_allow_origins: ~
      access_control_allow_credentials: ~
      access_control_allow_methods: ~
      access_control_allow_headers: ~
      access_control_allow_origin_regex: ~
      access_control_max_age: ~
      access_control_expose_headers: ~
    response:
      trace_id: false
  grpc:
    host: 0.0.0.0
    port: 3000
    max_concurrent_streams: ~
    maximum_concurrent_rpcs: ~
    max_message_length: -1
    reflection:
      enabled: false
    channelz:
      enabled: false
    metrics:
      host: 0.0.0.0
      port: 3001
  monitoring:
    enabled: true
    type: default
    options:
      log_config_file: ~
      log_path: monitoring
  tracing:
    exporter_type: ~
    sample_rate: ~
    excluded_urls: ~
    timeout: ~
    max_tag_value_length: ~
    zipkin:
      endpoint: ~
      local_node_ipv4: ~
      local_node_ipv6: ~
      local_node_port: ~
    jaeger:
      protocol: thrift
      collector_endpoint: ~
      thrift:
        agent_host_name: ~
        agent_port: ~
        udp_split_oversized_batches: ~
      grpc:
        insecure: ~
    otlp:
      protocol: ~
      endpoint: ~
      compression: ~
      http:
        certificate_file: ~
        headers: ~
      grpc:
        headers: ~
        insecure: ~
