# If someone with write access comments "/test-e2e" on a pull request, emit a repository_dispatch event
 name: slash-commands-dispatch

 on:
   issue_comment:
     types: [created]

 jobs:
   test-e2e-yatai:
     runs-on: ubuntu-latest
     # Only run for PRs, not issue comments
     if: ${{ github.event.issue.pull_request }}
     steps:
       # Generate a GitHub App installation access token from an App ID and private key
       # To create a new GitHub App:
       #   https://developer.github.com/apps/building-github-apps/creating-a-github-app/
       # See app.yml for an example app manifest
       - name: Generate token
         id: generate_token
         uses: tibdex/github-app-token@v1
         with:
           app_id: ${{ secrets.APP_ID }}
           private_key: ${{ secrets.PRIVATE_KEY }}

       - name: Slash Command Dispatch
         uses: peter-evans/slash-command-dispatch@v2
         env:
           TOKEN: ${{ steps.generate_token.outputs.token }}
         with:
           token: ${{ env.TOKEN }} # GitHub App installation access token
           # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # PAT or OAuth token will also work
           reaction-token: ${{ secrets.PAT_FOR_TEST}}
           issue-type: pull-request
           commands: test-e2e-yatai
           named-args: true
           permission: write

   help-command:
     runs-on: ubuntu-latest
     steps:
       # Checkout is necessary here due to referencing a local action.
       # It's also necessary when using the 'config-from-file' option.
       # Otherwise, avoid using checkout to keep this workflow fast.
       - uses: actions/checkout@v2

       - name: slash command dispatch
         uses: peter-evans/slash-command-dispatch@v2
         with:
           token: ${{ secrets.PAT_FOR_TEST }}
           commands: help
           permission: none
           issue-type: both
